### ISSUE TITLE
tries to run livestreamer from wrong location

### ISSUE THREAD

**Issue by DocTabasco** [sleighsoft/VLClive#2]
the instructions in the readme say to install livestreamer in the vlc instalation directory, which for me is C:\Program Files (x86)\VideoLAN\VLC
The extention then tries to load it from C:\Users\(user)\AppData\Roaming\vlc\lua\extensions\userdata\vlclive\livestreamer
using VLC 2.1.5 on Windows 8.1 x64

**Comment by sleighsoft** [comment]
Hello :)
I did some changes some time ago, but due to no feedback I did not update the readme etc.
I currently don't have much time but I'll try to update the readme and give some more instructions on how it works.

Thanks for your feedback and stay tuned :+1:

**Comment by sleighsoft** [comment]
I changed it to only accept livestreamer if you set it as a path variable under windows and other OSs
