### ISSUE TITLE
[feature-request] Get list of channels being followed by the user

### ISSUE THREAD

**Issue by denilsonsa** [sleighsoft/VLClive#6]
Suggestion: the plugin could allow me to just fill in my twitch username, and it would populate the list of favorites .

It can be done using [/users/:user/follows/channels](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#get-usersuserfollowschannels) API, which may require including a JSON decoding library into the plugin.

**Comment by sleighsoft** [comment]
Brilliant idea, I will look into it when I have some spare time. 

Keep coming with good ideas :)

**Comment by sleighsoft** [comment]
Added the requested feature in the new commit!
I hope you like it :)
Feel free to write any feedback to it.

**Comment by denilsonsa** [comment]
You introduced a typo: `availabel`

Thanks for implementing it! It worked!

I'm now having another issue:

> [0x7f34ec045048] gnutls tls client error: TLS handshake error: A TLS fatal alert has been received.
> [0x7f34ec045048] main tls client error: TLS client session handshake error
> [0x7f34ec004998] access_http access error: cannot establish HTTP/TLS session
> [0x7f34f42e0cc8] main generic error: no suitable access module for `https://api.twitch.tv/kraken/streams?channel=…'

Probably some error on my side, I should probably update my system. Anyway, feel free to close this issue.

**Comment by sleighsoft** [comment]
This might be due to an outdated version of VLC.
Some do not support gnutls.

**Comment by denilsonsa** [comment]
Indeed. I've updated my Linux system and now that error is gone. Thanks!
