### ISSUE TITLE
Fav lists importing? wrong

### ISSUE THREAD

**Issue by Frankthetankk** [sleighsoft/VLClive#7]
using v1.0 on windows. The favorites list isnt showing from my twitch account. The list is showing twitch streamers that are not my favorites. For example some of the names in the dropdown list that I do not follow on twitch are goldglove, timmac, datmodz.

**Comment by sleighsoft** [comment]
Hmm, what is your twitch name?

**Comment by Frankthetankk** [comment]
Took me a bit to figure out what's going on, but now I'm able to understand the steps I took to reach this bug. After installing a fresh copy of VLClive, I wanted to add my favorite streamers. I must of misunderstood the usage directions, because in the 'User favourites' field I thought we were suppose to individually add each of our favorites to the list. The field description is a little misleading. In my fresh copy, I began with the streamer Lirik and then clicked on 'add twitch favorites'. I didn't understand it at the time, but one bug is that VLClive imported Lirik's favorites to the list, and it only imported Lirik's topmost 25 favorites and not his entire favorites(72 followers currently). Now that I've understand the correct usage for this field, I tried entering in my twitch username to add my fav's. I noticed that it successfully enters in a small handful of my fav's, but it's far from the completed list. Also the list is mixed in with my failed attempt with adding Liriks fav's, and there is no way I can figure out how to clear the list or remove ones I don't want on the list.

As a request, is it possible to filter the online streamers towards the top of the dropdown, colorcode them, show their profile photos next to their names, or perhaps have a checkmark to only display online streamers? I would like to reorder the fav list to my likings. Hope this made sense. Thanks.

**Comment by sleighsoft** [comment]
I took a look into it and it seems that by default twitch api returns only 25 items.
I'll fix that as soon as possible.
Thank you for reporting :)

**Comment by sleighsoft** [comment]
1. Do you know any account that follows more than 100 people, so I can test if my new implementation works?
2. Do you have any naming suggestions for the misleading labels?

**Comment by Frankthetankk** [comment]
http://www.twitch.tv/giantwaffle/profile/following has 213 he's following.

You could say something like "For importing a list, Enter a Twitch.tv user(channel?) name"

**Comment by Frankthetankk** [comment]
I just tried your update. When clicking on Watch stream, vlc flashes once and closes. 
The list still displays streamers from my importing the wrong username. Also after importing a user with over 100 followers it'll only display those 100 ignoring the rest, even if they're currently online.

**Comment by sleighsoft** [comment]
Ok, I updated the file again.
If you want to bulk delete all streamers you can do the following.
Assuming you are on Windows:
Go to -> C:\Users\<YourUsername>\AppData\Roaming\vlc\lua\extensions\userdata\vlclive
and delete or clear the vlclive.config file. Then try adding all your favourites again.

**Comment by Frankthetankk** [comment]
Deleting the config file fixed clearing/removing streamers. The fav list appears to be working now as intended. Thanks.

The watch stream button is now broken. When clicking on Watch stream, vlc flashes once and closes.

**Comment by sleighsoft** [comment]
I might have broken something along the way :(
I also have an idea where :D
I'll jump back some commits to a working version so people can continue using the plugin and I'll look into fixing it later.

**Comment by sleighsoft** [comment]
Did some more bug fixing.
As always I am happy about any bugs you might find ^^

**Comment by Frankthetankk** [comment]
It's working now.

For a feature request. Consider adding a 'Currently viewing' field, and/or a recently viewed streamers(maybe filter this to the top of the dropdown list).

**Comment by Frankthetankk** [comment]
Is it possible to sort the online list based on current viewers?

**Comment by sleighsoft** [comment]
That is possible. 
I will implement that option as well, but it might take some time as I intend to do a code clean up before I implement new features. 
Does everything work for you now?

**Comment by Frankthetankk** [comment]
Yes it appears to be working now. Thanks

To further expand on my previous requests. I'd like to be able to have an option to only display streamers that are online. I'd like to see a 'Currently viewing' field, 'Recently viewed' field. Perhaps somewhere related to the dropdown fav's, I'd like to see the current channel Title(which can get long) next to the streamers name, also I'd like to see the current game title being played and a Thumbnail from each of the online streamers.

**Comment by sleighsoft** [comment]
I can see what I can do.
My schedule is pretty full right now so it might take some time.
There is also the limitation of the Lua GUI for VLC which only allows certain graphical elements like dropdown, button and checklist.
I'll keep you updated when new features come out.
Thank you for your suggestions and feedback!
